# Generated by Marten 0.2.3 on 2023-04-15 13:42:03 -03:00

class Migration::Main::V202304151342031 < Marten::Migration
  def plan
    create_table :main_article do
      column :id, :big_int, primary_key: true, auto: true
      column :title, :string, max_size: 255
      column :content, :text
    end
  end
end
