name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build and push Docker image
        env:
          DOCKER_BUILDKIT: 1
          IMAGE_NAME: myuser/final-app
        run: |
          docker build -t $IMAGE_NAME:latest .
          echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker push $IMAGE_NAME:latest
