version: '3'

networks:
  services_network:
    external: false

services:
  redis:
    image: redis:6-alpine
    command: redis-server
    container_name: tasks_redis
    ports:
      - '6379:6379'
    networks:
      - services_network
