@baseUrl = http://localhost:3000
@contentType = application/json

###
# @name index
GET {{baseUrl}} HTTP/1.1

###
# @name openapi
GET {{baseUrl}}/openapi HTTP/1.1

###
# @name getOtherRoute
GET {{baseUrl}}/api/other/route HTTP/1.1

###
# @name getExample
# @prompt example
GET {{baseUrl}}/api/{{example}} HTTP/1.1

###
# @name postExample
# @prompt example
POST {{baseUrl}}/api/{{example}} HTTP/1.1
Content-Type: {{contentType}}

{
    "example": "{{example}}"
}
