version: '3.8'

services:
  lgtm:
    image: docker.io/grafana/otel-lgtm:0.11.4
    container_name: lgtm
    ports:
      - "3000:3000"    # Grafana
      - "4317:4317"    # OTLP gRPC
      - "4318:4318"    # OTLP HTTP
    volumes:
      - ./lgtm/grafana:/data/grafana
      - ./lgtm/prometheus:/data/prometheus
      - ./lgtm/loki:/data/loki
    environment:
      - GF_PATHS_DATA=/data/grafana
    restart: unless-stopped
    networks:
      - observability

  promtail:
    image: grafana/promtail:2.9.3
    container_name: promtail
    volumes:
      - /var/log:/var/log
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./promtail-config.yaml:/etc/promtail/config.yaml
      - promtail-positions:/var/lib/promtail
    command: -config.file=/etc/promtail/config.yaml
    restart: unless-stopped
    networks:
      - observability
    depends_on:
      - lgtm

  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myapp
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - observability
    depends_on:
      - lgtm
      - promtail

volumes:
  promtail-positions:

networks:
  observability:
    driver: bridge
