server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /var/lib/promtail/positions.yaml

clients:
  - url: http://lgtm:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*.log
    pipeline_stages:
      - json:
          expressions:
            stream: stream
            time: time
            log: log
      - json:
          expressions:
            timestamp: timestamp
            severity: severity
            message: message
            httpRequest: httpRequest
            traceparent: traceparent
          source: log
      - labels:
          stream:
          severity:
      - timestamp:
          source: timestamp
          format: RFC3339
      - output:
          source: message

  - job_name: myapp
    static_configs:
      - targets:
          - localhost
        labels:
          job: myapp
          app: crystal-nginx
          __path__: /var/lib/docker/containers/myapp*/*.log
    pipeline_stages:
      - json:
          expressions:
            stream: stream
            time: time
            log: log
      - json:
          expressions:
            timestamp: timestamp
            severity: severity
            message: message
            httpRequest: httpRequest
            traceparent: traceparent
          source: log
      - labels:
          stream:
          severity:
      - timestamp:
          source: timestamp
          format: RFC3339
      - output:
          source: message
