version: '3'

networks:
  services_network:
    external: false

services:
  postgres:
    image: postgres:14-alpine
    container_name: tasks_postgres
    environment:
      - POSTGRES_DB=tasks
      - POSTGRES_USER=tasks
      - POSTGRES_PASSWORD=tasks
    ports:
      - '5432:5432'
    volumes:
      - '.docker/postgres:/var/lib/postgresql/data'
    networks:
      - services_network
